# Generated by Django 6.0.3 on 2026-03-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('enrolled_in', models.CharField(max_length=100)),
            ],
        ),
    ]
